routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductGalleriesController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\LaporanController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\LandingPageController::class, 'index'])->name('landingpage');
Route::get('/detail/{id}', [App\Http\Controllers\LandingPageController::class, 'detail'])->name('detail');
Route::post('/detail/{id}', [App\Http\Controllers\LandingPageController::class, 'add'])->name('detail-add');

Route::get('/categories', [App\Http\Controllers\LandingPageController::class, 'categories'])->name('categories');

Route::post('/addreview/{id}',[App\Http\Controllers\LandingPageController::class, 'addreview'])->name('addreview');
Route::get('/orderhistory',[App\Http\Controllers\LandingPageController::class, 'orderhistory'])->name('order-history');
Route::put('/uploadBukti', [App\Http\Controllers\LandingPageController::class, 'uploadBukti'])->name('uploadBukti');
Route::post('/addBukti', function(Request $request){
    $request->validate([
        'user_id' => 'required',
        'id_transaksi' => 'required',
        'file' => 'required',
        'file.*' => 'mimes:doc,docx,PDF,pdf,jpg,jpeg,png|max:2000'
    ]);
    if ($request->hasfile('file')) {            
        $filename = str_replace(' ','-',$request->file('file')->getClientOriginalName());
        $request->file('file')->move(\storage_path('bukti'), $filename);
        Pembayaran::insert([                        
            'id_transaksi' => $request->id_transaksi,
            'user_id' => $request->user_id,
            'image' =>$filename,
        ]);
        return redirect('/orderhistory');
    }else{
        echo'Gagal';
    }
})->name('addBukti');
Route::post('/show-order/{id}',[App\Http\Controllers\LandingPageController::class, 'ordershow'])->name('ordershow');
Route::get('/about-me',[App\Http\Controllers\LandingPageController::class, 'aboutme'])->name('aboutme');


Auth::routes();

Route::post('/home/upload', [HomeController::class, 'index'])->name('upload');

Route::middleware(['auth', 'admin'])
    ->group(function() {

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::resource('product', ProductController::class);
Route::resource('transaction', TransactionController::class);
Route::resource('product-galleries', ProductGalleriesController::class);
Route::get('laporan', [LaporanController::class, 'index']);

    });

Route::resource('cart', CartController::class);

Route::post('/checkout', [App\Http\Controllers\CheckoutController::class, 'process'])->name('checkout');
Route::post('/checkout/callback', [App\Http\Controllers\CheckoutController::class, 'callback'])->name('midtrans-callback');
Route::post('/order', [App\Http\Controllers\CheckoutController::class, 'order'])->name('order');

Route::post('/checkoutdata', [App\Http\Controllers\CheckoutController::class, 'checkoutdata'])->name('checkoutdata');

resources/views/frontend/LandingPage.blade.php
@extends('frontend.include.app')
@section('content')
    <div class="page-content page-home">
        <section class="store-carousel">
            <div class="container">
            @if (session('message'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Selamat!</strong> {{ session('message') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif
            @if (session('error'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Peringatan!</strong> {{ session('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif
                <div class="row">
                    <div class="col-lg-12" data-aos="zoom-in">
                        <div id="storeCarousel" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#storeCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#storeCarousel" data-slide-to="1"></li>
                                <li data-target="#storeCarousel" data-slide-to="2"></li>
                                <li data-target="#storeCarousel" data-slide-to="3"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img src="{{ asset('frontend/images/banner1.jpg') }}" height="600px"
                                        style="border-radius: 20px" class="d-block w-100 " alt="Carousel Image" />
                                </div>
                                <div class="carousel-item">
                                    <img src="{{ asset('frontend/images/banner2.jpg') }}" class="d-block w-100 "
                                        style="border-radius: 20px" height="600px" alt="Carousel Image" />
                                </div>
                                <div class="carousel-item">
                                    <img src="{{ asset('frontend/images/banner3.jpg') }}" class="d-block w-100 "
                                        style="border-radius: 20px" height="600px" alt="Carousel Image" />
                                </div>
                                <div class="carousel-item">
                                    <img src="{{ asset('frontend/images/banner4.jpg') }}" class="d-block w-100 "
                                        style="border-radius: 20px" height="600px" alt="Carousel Image" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="store-trend-categories">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center" data-aos="fade-up">
                        <h5 class="text-center"> Category</h5>
                        <img src="{{ asset('frontend/images/logo1.png') }}" alt="">
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-6 col-md-3 col-lg-4" data-aos="fade-up" data-aos-delay="200">
                        <div class="component-categories d-block">
                            <div class="categories-image">
                                <img src="{{ asset('frontend/images/dessert.jpg') }}" alt="Gadgets Categories"
                                    class="w-100" height="217px" />
                            </div>
                            <p class="categories-text">
                                Dessert Box
                            </p>
                        </div>
                    </div>
                    <div class="col-6 col-md-3 col-lg-4" data-aos="fade-up" data-aos-delay="600">
                        <div class="component-categories d-block">
                            <div class="categories-image">
                                <img src="{{ asset('frontend/images/milo.jpg') }}" alt="Furniture Categories"
                                    class="w-100" height="217px" />
                            </div>
                            <p class="categories-text">
                                Dessert Cup
                            </p>
                        </div>
                    </div>
                    <div class="col-6 col-md-3 col-lg-4" data-aos="fade-up" data-aos-delay="400">
                        <div class="component-categories d-block">
                            <div class="categories-image">
                                <img src="{{ asset('frontend/images/brownies.jpg') }}" alt="Makeup Categories"
                                    class="w-100" height="217px" />
                            </div>
                            <p class="categories-text">
                                Baked Brownies
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="store-trend-categories">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center" data-aos="fade-up">
                        <h5 class="text-center"> Suggest Menu</h5>
                        <img src="{{ asset('frontend/images/logo2.png') }}" alt="">
                    </div>
                </div>
                <div class="row mt-4 ">
                    @php $incrementProduct = 0 @endphp
                    @foreach ($suggestproduct as $item)
                        <div class="col-6 col-md-3 col-lg-4 pt-3" data-aos="fade-up"
                            data-aos-delay="{{ $incrementProduct += 100 }}">
                            <a class=" d-block" style="text-decoration:none" href="{{ route('detail', $item->id) }}">
                                <p class="categories-text ">
                                    <h4 class="text-center"> {{ $item->ProductName }} </h4>
                                </p>
                                <div class="categories-image">
                                    <img src="{{ asset('foto/' . $item->galleries->first()->Photos) }}" alt="Gadgets Categories" class="w-100" height="217px" />


                                    {{-- <img src="https://wedding.skripti.xyz//thome/img/2.jpg" alt="Gadgets Categories" class="w-100" height="217px" /> --}}
                                </div>
                                <p class="categories-text ">
                                    <h6 class="text-center"> {{ $item->Categories }} </h6>
                                </p>
                            </a>
                        </div>
                    @endforeach
                </div>
            </div>
        </section>

        <section class="store-new-products mt-5">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center" data-aos="fade-up">
                        <h5 class="text-center">New Menu </h5>
                        <img src="{{ asset('frontend/images/logo2.png') }}" width="80px" height="57px" alt="">
                    </div>
                </div>
                <div class="row mt-5">
                    @php $incrementProduct = 0 @endphp
                    @foreach ($data as $item)
                        <div class="col-6 col-md-4 col-lg-3" data-aos="fade-right"
                            data-aos-delay="{{ $incrementProduct += 100 }}">
                            <a class="component-products d-block" href="{{ route('detail', $item->id) }}">
                                <div class="products-thumbnail">
                                    <div class="products-image"
                                        style="background-image: url('{{ asset('foto/' . $item->galleries->first()->Photos) }}');">


                                    </div>
                                </div>
                                <div class="products-text">
                                    {{ $item->ProductName }}
                                </div>
                                <div class="products-price">
                                     Rp {{ number_format($item->Price) }}
                                </div>
                            </a>
                        </div>
                    @endforeach
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/frontend/about.blade.php
@extends('frontend.include.app')

@section('content')

    <!-- Page Content -->
    <div class="page-content page-categories">
        <section class="store-trend-categories">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center" data-aos="fade-up">
                        <h5 class="text-center"> About Us </h5>
                        <img src="{{ asset('frontend/images/logo1.png') }}" alt="">
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-md-12  col-sm-12 col-lg-6" data-aos="fade-up" data-aos-delay="600">
                        <div class="component-categories d-block">
                            <div class="categories-image text-center" style="height: 455px">
                               <h5> Sweetbites by Caca merupakan sebuah <br /> home industry yang berlokasi di Jagakarsa dan dikelola langsung oleh seorang mahasiswi dari Universitas Gunadarma. Pada awalnya owner hanya menjual satu macam saja yaitu Regal Dessert Box. Namun karena banyaknya permintaan dari berbagai belah pihak kini Sweetbites By Caca juga menjual berbagai menu lainnya. <br /> <br /> So, what do you waiting for? <br /> Let's buy some! ^^ </h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 col-sm-12 col-lg-6" data-aos="fade-up" data-aos-delay="400">
                        <div class="component-categories d-block">
                            <div class="categories-image">
                                <img src="{{ asset('frontend/images/dessert.jpg') }}" alt="Gadgets Categories"
                                    class="w-100" height="400px" />
                            </div>
                            <p class="categories-text">
                                Regal Dessert Box
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@section('fixed','fixed-bottom')
    

    

resources/views/frontend/paymentorder.blade.php
@extends('frontend.include.app')

@section('title')
    Store Cart Page
@endsection

@section('content')
    <!-- Page Content -->
    <div class="page-content page-cart">
        <section class="store-breadcrumbs" data-aos="fade-down" data-aos-delay="100">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Cart
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
        <section class="store-cart">
            <div class="container">
                <div class="row" data-aos="fade-up" data-aos-delay="100">
                    <div class="col-12 table-responsive">
                        <table class="table table-borderless table-cart" aria-describedby="Cart">
                            <thead>
                                <tr>
                                    <th scope="col">Image</th>
                                    <th scope="col">Name Menu</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Shipping</th>
                                    <th scope="col">Quantity</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $totalPrice = 0 @endphp
                                @foreach ($carts as $cart)
                                    <tr>
                                        <div class="row">
                                            <div class="col-md-2">
                                                <td>
                                                    @if ($cart->product->galleries)
                                                        <img src="{{ asset('foto/' . $cart->product->galleries->first()->Photos) }}" alt="" class="cart-image" />
                                                    @endif
                                                </td>
                                            </div>
                                            <div class="col-md-2">
                                                <td>
                                                    <div class="product-title">{{ $cart->product->ProductName }}</div>
                                                </td>
                                            </div>
                                            <div class="col-md-2">
                                                <td>
                                                    <div class="product-title">{{ number_format($cart->product->Price * $cart->Quantity) }}</div>
                                                    <div class="product-subtitle"></div>
                                                </td>
                                            </div>
                                            <div class="col-md-2">
                                                <td>
                                                    <div class="product-title">{{ number_format(20000) }}</div>
                                                    <div class="product-subtitle"></div>
                                                </td>
                                            </div>
                                            <div class="col-md-2">
                                                <td>
                                                    <div class="product-title">{{ $cart -> Quantity }}</div>
                                                    <div class="product-subtitle"></div>
                                                </td>
                                            </div>
                                        </div>
                                    </tr>
                               
                                    @php $totalPrice += $cart->product->Price @endphp
                                    @php $allprice = $totalPrice * $cart->Quantity + 20000 @endphp
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row" data-aos="fade-up" data-aos-delay="150">
                    <div class="col-12">
                        <hr />
                    </div>
                    <div class="col-12">
                        <h2 class="mb-4">Shipping Details</h2>
                    </div>
                </div>
                <form action="{{ route('checkout') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" class="form-control" name="name" value="{{ $name }}" />
                    <input type="hidden" class="form-control" name="email" value="{{ $email }} " />
                    <input type="hidden" class="form-control" name="address_one" value="{{ $address_one }} " />
                    <input type="hidden" class="form-control" name="address_two" value="{{ $address_two }} " />
                    <input type="hidden" class="form-control" name="province" value="{{ $province }} " />
                    <input type="hidden" class="form-control" name="city" value="{{ $city }} " />
                    <input type="hidden" class="form-control" name="zip_code" value="{{ $zip_code }} " />
                    <input type="hidden" class="form-control" name="phone" value="{{ $phone }} " />
                    <input type="hidden" class="form-control" name="total_price" value="{{ $allprice }} " />
                    <div class="row mb-2" data-aos="fade-up" data-aos-delay="200" id="locations">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="address_one">Name </label>
                                <h5> {{ $name }}
                                </h5>
                            </div>
                        </div>
                        <div class=" col-md-6">
                            <div class="form-group">
                                <label for="address_one">Mail </label>
                                <h5> {{ $email }}
                                </h5>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="address_one">Address 1</label>
                                <h5> {{ $address_one }}
                                </h5>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="address_two">Address 2</label>
                                <h5> {{ $address_two }}
                                </h5>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="provinces_id">Province</label>
                                <h5> {{ $province }}
                                </h5>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="city">City</label>
                                <h5> {{ $city }}
                                </h5>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="zip_code">Postal Code</label>
                                <h5> {{ $zip_code }}
                                </h5>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="phone_number">Mobile Phone</label>
                                <h5> {{ $phone }}
                                </h5>
                            </div>
                        </div>
                    </div>
                    <div class="row" data-aos="fade-up" data-aos-delay="150">
                        <div class="col-12">
                            <hr />
                        </div>
                        <div class="col-12">
                            <h2 class="mb-1">Payment Informations</h2>
                        </div>
                    </div>
                    <div class="row" data-aos="fade-up" data-aos-delay="200">
                        <div class="col-4 col-md-2">
                            <div class="product-title"> <img src="{{ asset('frontend/images/ic_bank.png') }}" alt="">
                            </div>
                            <div class="product-subtitle">Transfer Bank</div>
                        </div>
                        <div class="col-4 col-md-4">
                            <div class="product-title"> 
                                A/n Salsabila Endang Saf
                            </div>
                            <div class="product-subtitle">1270009890821 - Mandiri</div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="product-title text-success">{{ number_format($totalPrice * $cart->Quantity + 20000) }}</div>
                            <div class="product-subtitle">Total</div>
                        </div>
                        <div class="col-12 col-md-6">
                            <button type="submit" class="btn btn-success mt-4 px-4 btn-block">
                                Continue Payment
                            </button>
                        </div>
                        <div class="col-12 col-md-6">
                            <a href="{{route('cart.index')}}" class="btn btn-success mt-4 px-4 btn-block text-white">
                                Cancel 
                            </a>
                        </div>
                    </div>
                </form>
              
            </div>
        </section>
    </div>
@endsection

{{-- @push('addon-script')
    <script src="/vendor/vue/vue.js"></script>
    <script src="https://unpkg.com/vue-toasted"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        var locations = new Vue({
            el: "#locations",
            mounted() {
                this.getProvincesData();
            },
            data: {
                provinces: null,
                regencies: null,
                provinces_id: null,
                regencies_id: null,
            },
            methods: {
                getProvincesData() {
                    var self = this;
                    axios.get('{{ route('api-provinces') }}')
                        .then(function(response) {
                            self.provinces = response.data;
                        })
                },
                getRegenciesData() {
                    var self = this;
                    axios.get('{{ url('api/regencies') }}/' + self.provinces_id)
                        .then(function(response) {
                            self.regencies = response.data;
                        })
                },
            },
            watch: {
                provinces_id: function(val, oldVal) {
                    this.regencies_id = null;
                    this.getRegenciesData();
                },
            }
        });

    </script>
@endpush --}}

resources/views/frontend/riwayat.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>
    <div class="container">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Larry</td>
                    <td>the Bird</td>
                    <td>@twitter</td>
                </tr>
            </tbody>
        </table>
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>
</html>