routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductGalleriesController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\LaporanController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\LandingPageController::class, 'index'])->name('landingpage');
Route::get('/detail/{id}', [App\Http\Controllers\LandingPageController::class, 'detail'])->name('detail');
Route::post('/detail/{id}', [App\Http\Controllers\LandingPageController::class, 'add'])->name('detail-add');

Route::get('/categories', [App\Http\Controllers\LandingPageController::class, 'categories'])->name('categories');

Route::post('/addreview/{id}',[App\Http\Controllers\LandingPageController::class, 'addreview'])->name('addreview');
Route::get('/orderhistory',[App\Http\Controllers\LandingPageController::class, 'orderhistory'])->name('order-history');
Route::put('/uploadBukti', [App\Http\Controllers\LandingPageController::class, 'uploadBukti'])->name('uploadBukti');
Route::post('/addBukti', function(Request $request){
    $request->validate([
        'user_id' => 'required',
        'id_transaksi' => 'required',
        'file' => 'required',
        'file.*' => 'mimes:doc,docx,PDF,pdf,jpg,jpeg,png|max:2000'
    ]);
    if ($request->hasfile('file')) {            
        $filename = str_replace(' ','-',$request->file('file')->getClientOriginalName());
        $request->file('file')->move(\storage_path('bukti'), $filename);
        Pembayaran::insert([                        
            'id_transaksi' => $request->id_transaksi,
            'user_id' => $request->user_id,
            'image' =>$filename,
        ]);
        return redirect('/orderhistory');
    }else{
        echo'Gagal';
    }
})->name('addBukti');
Route::post('/show-order/{id}',[App\Http\Controllers\LandingPageController::class, 'ordershow'])->name('ordershow');
Route::get('/about-me',[App\Http\Controllers\LandingPageController::class, 'aboutme'])->name('aboutme');


Auth::routes();

Route::post('/home/upload', [HomeController::class, 'index'])->name('upload');

Route::middleware(['auth', 'admin'])
    ->group(function() {

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::resource('product', ProductController::class);
Route::resource('transaction', TransactionController::class);
Route::resource('product-galleries', ProductGalleriesController::class);
Route::get('laporan', [LaporanController::class, 'index']);

    });

Route::resource('cart', CartController::class);

Route::post('/checkout', [App\Http\Controllers\CheckoutController::class, 'process'])->name('checkout');
Route::post('/checkout/callback', [App\Http\Controllers\CheckoutController::class, 'callback'])->name('midtrans-callback');
Route::post('/order', [App\Http\Controllers\CheckoutController::class, 'order'])->name('order');

Route::post('/checkoutdata', [App\Http\Controllers\CheckoutController::class, 'checkoutdata'])->name('checkoutdata');

resources/views/backend/include/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    @include('frontend.include.head')
</head>

<body>
    <div class="page-dashboard">
        <div class="d-flex" id="wrapper">
            @include('backend.include.sidebar')
            <div id="page-content-wrapper">
                <div id="page-content-wrapper">
                    <nav class="navbar navbar-store navbar-expand-lg navbar-light fixed-top" >
                        <button class="btn btn-secondary d-md-none mr-auto mr-2" id="menu-toggle">
                            &laquo; Menu
                        </button>
              
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
              
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto d-none d-lg-flex">
                                <li class="nav-item dropdown">
                                    <a class="nav-link" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                        <img src="{{ asset('frontend/images/logo2.png')}}" alt="" class="rounded-circle mr-2 profile-picture" />
                                        Hi, {{ Auth::user()->name}} 
                                        <form action="{{route('logout')}}" class="d-inline" method="POST">
                                            @csrf
                                            <button type="submit" class="d-inline btn btn-info"> Logout </button>
                                        </form>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                        <a class="dropdown-item" href="/index.html">Back to Store</a>
                                        <a class="dropdown-item" href="/dashboard-account.html">Settings</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="/">Logout</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link d-inline-block mt-2" href="">
                                        <img src="/images/icon-cart-empty.svg" alt="" />
                                    </a>
                                </li>
                            </ul>
                            <!-- Mobile Menu -->
                            <ul class="navbar-nav d-block d-lg-none mt-3">
                                <li class="nav-item">
                                    <a class="nav-link" href="#">
                                        Hi, {{ Auth::user()->name}}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link d-inline-block" href="#">
                                        Cart
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                    @yield('content')
                </div>
            </div>
        </div>
    </div>

    @include('frontend.include.footer')

</body>

</html>

resources/views/backend/include/appGrafik.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    @include('frontend.include.head')
</head>

<body>
    <div class="page-dashboard">
        <div class="d-flex" id="wrapper">
            @include('backend.include.sidebar')
            <div id="page-content-wrapper">
                <div id="page-content-wrapper">
                    <nav class="navbar navbar-store navbar-expand-lg navbar-light fixed-top">
                        <button class="btn btn-secondary d-md-none mr-auto mr-2" id="menu-toggle">
                            &laquo; Menu
                        </button>

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto d-none d-lg-flex">
                                <li class="nav-item dropdown">
                                    <a class="nav-link" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <img src="{{ asset('frontend/images/logo2.png')}}" alt="" class="rounded-circle mr-2 profile-picture" />
                                        Hi, {{ Auth::user()->name}}
                                        <form action="{{route('logout')}}" class="d-inline" method="POST">
                                            @csrf
                                            <button type="submit" class="d-inline btn btn-info"> Logout </button>
                                        </form>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                        <a class="dropdown-item" href="/index.html">Back to Store</a>
                                        <a class="dropdown-item" href="/dashboard-account.html">Settings</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="/">Logout</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link d-inline-block mt-2" href="">
                                        <img src="/images/icon-cart-empty.svg" alt="" />
                                    </a>
                                </li>
                            </ul>
                            <!-- Mobile Menu -->
                            <ul class="navbar-nav d-block d-lg-none mt-3">
                                <li class="nav-item">
                                    <a class="nav-link" href="#">
                                        Hi, {{ Auth::user()->name}}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link d-inline-block" href="#">
                                        Cart
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                    @yield('content')
                </div>
            </div>
        </div>
    </div>

    @include('frontend.include.footer')
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar', 
            data: {
                labels: ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']
                , datasets: [{
                    label: '# Grafik pendapatan perbulan'
                    , data: [{!! json_encode($januari) !!}, {!! json_encode($februari) !!}, {!! json_encode($maret) !!}, {!! json_encode($april) !!}, {!! json_encode($mei) !!}, {!! json_encode($juni) !!}, {!! json_encode($juli) !!}, {!! json_encode($agustus) !!}, {!! json_encode($september) !!}, {!! json_encode($oktober) !!}, {!! json_encode($november) !!}, {!! json_encode($desember) !!}]
                    , backgroundColor: [
                        'rgba(255, 99, 132, 0.2)'
                        , 'rgba(54, 162, 235, 0.2)'
                        , 'rgba(255, 206, 86, 0.2)'
                        , 'rgba(75, 192, 192, 0.2)'
                        , 'rgba(153, 102, 255, 0.2)'
                        , 'rgba(255, 159, 64, 0.2)'
                    ]
                    , borderColor: [
                        'rgba(255, 99, 132, 1)'
                        , 'rgba(54, 162, 235, 1)'
                        , 'rgba(255, 206, 86, 1)'
                        , 'rgba(75, 192, 192, 1)'
                        , 'rgba(153, 102, 255, 1)'
                        , 'rgba(255, 159, 64, 1)'
                    ]
                    , borderWidth: 1
                }]
            }
            , options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>


</body>

</html>

resources/views/backend/include/sidebar.blade.php
   <div class="border-right" id="sidebar-wrapper">
       <div class="sidebar-heading text-center">
           <img src="{{ asset('frontend/images/logo1.png')}}" alt="" class="my-4" />
       </div>
       <div class="list-group list-group-flush">
           <a href="{{ route('dashboard') }}" class="list-group-item list-group-item-action active">Dashboard Admin</a>
           <a href="{{ route('product.index') }}" class="list-group-item list-group-item-action">My Menu</a>
           <a href="{{ route('product-galleries.index') }}" class="list-group-item list-group-item-action">Menu Galleries</a>
           <a href="{{ route('transaction.index') }}" class="list-group-item list-group-item-action">Transactions</a>
           {{-- <a href="{{ url('laporan') }}" class="list-group-item list-group-item-action">Laporan</a> --}}
       </div>
   </div>