routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductGalleriesController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\LaporanController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\LandingPageController::class, 'index'])->name('landingpage');
Route::get('/detail/{id}', [App\Http\Controllers\LandingPageController::class, 'detail'])->name('detail');
Route::post('/detail/{id}', [App\Http\Controllers\LandingPageController::class, 'add'])->name('detail-add');

Route::get('/categories', [App\Http\Controllers\LandingPageController::class, 'categories'])->name('categories');

Route::post('/addreview/{id}',[App\Http\Controllers\LandingPageController::class, 'addreview'])->name('addreview');
Route::get('/orderhistory',[App\Http\Controllers\LandingPageController::class, 'orderhistory'])->name('order-history');
Route::put('/uploadBukti', [App\Http\Controllers\LandingPageController::class, 'uploadBukti'])->name('uploadBukti');
Route::post('/addBukti', function(Request $request){
    $request->validate([
        'user_id' => 'required',
        'id_transaksi' => 'required',
        'file' => 'required',
        'file.*' => 'mimes:doc,docx,PDF,pdf,jpg,jpeg,png|max:2000'
    ]);
    if ($request->hasfile('file')) {            
        $filename = str_replace(' ','-',$request->file('file')->getClientOriginalName());
        $request->file('file')->move(\storage_path('bukti'), $filename);
        Pembayaran::insert([                        
            'id_transaksi' => $request->id_transaksi,
            'user_id' => $request->user_id,
            'image' =>$filename,
        ]);
        return redirect('/orderhistory');
    }else{
        echo'Gagal';
    }
})->name('addBukti');
Route::post('/show-order/{id}',[App\Http\Controllers\LandingPageController::class, 'ordershow'])->name('ordershow');
Route::get('/about-me',[App\Http\Controllers\LandingPageController::class, 'aboutme'])->name('aboutme');


Auth::routes();

Route::post('/home/upload', [HomeController::class, 'index'])->name('upload');

Route::middleware(['auth', 'admin'])
    ->group(function() {

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::resource('product', ProductController::class);
Route::resource('transaction', TransactionController::class);
Route::resource('product-galleries', ProductGalleriesController::class);
Route::get('laporan', [LaporanController::class, 'index']);

    });

Route::resource('cart', CartController::class);

Route::post('/checkout', [App\Http\Controllers\CheckoutController::class, 'process'])->name('checkout');
Route::post('/checkout/callback', [App\Http\Controllers\CheckoutController::class, 'callback'])->name('midtrans-callback');
Route::post('/order', [App\Http\Controllers\CheckoutController::class, 'order'])->name('order');

Route::post('/checkoutdata', [App\Http\Controllers\CheckoutController::class, 'checkoutdata'])->name('checkoutdata');

app/Models/ProductGallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductGallery extends Model
{
    use HasFactory;
    protected $table = 'product_galleries';
    protected $fillable = [
        'Photos','Products_id',
    ];

       public function product(){
        return $this->belongsTo(Product::class, 'Products_id', 'id');
    }

    
}

app/Http/Controllers/ProductGalleriesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\ProductGallery;
use Illuminate\Http\Request;

class ProductGalleriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $data =  ProductGallery::with('product')->get();
        return view('backend.product-galleries.index',compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Product::all();
        return view('backend.product-galleries.create',compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'Products_id' => 'required',
            'Photos.*' => 'required|mimes:jpg,jpeg,png',
        ]);

        $filename = str_replace(' ','-',$request->file('Photos')->getClientOriginalName());
        $request->file('Photos')->move(\public_path('foto'), $filename);
        

        $gallery = [
            'Products_id' => $request->Products_id,
            'Photos' =>  $filename,
        ];
        ProductGallery::create($gallery);
        
        // $gallery = [
        //     'Products_id' => $request -> Products_id,
        //     'Photos' =>  $request->file('Photos')->store('assets/product', 'public'),
        // ];

        // ProductGallery::create($gallery);

        return redirect('/product-galleries')->with('message', 'Data telah ditambahkan');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $data =   ProductGallery::with('product')->where('id',$id)->first();
        return view('backend.product-galleries.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        ProductGallery::findOrFail($id)->delete();

        return redirect('/product-galleries')->with('message', 'Data telah dihapus');
    }
}

resources/views/backend/product-galleries/create.blade.php
@extends('backend.include.app')

@section('content')

    <div class="section-content section-dashboard-home" >
        <div class="container-fluid">
            <div class="dashboard-heading">
                <h2 class="dashboard-title">Add New Menu</h2>
                <p class="dashboard-subtitle">
                    Create my own menu
                </p>
            </div>
            <div class="dashboard-content">
                <div class="row">
                    <div class="col-12">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('product-galleries.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class=" form-group">
                                                <label>Menu</label>
                                                <select name="Products_id" class="form-control">
                                                    @foreach ($data as $product)
                                                        <option value="{{ $product->id }}">{{ $product->ProductName }}
                                                        </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="thumbnails">Thumbnails</label>
                                                <input type="file" multiple class="form-control pt-1" id="thumbnails"
                                                    aria-describedby="thumbnails" name="Photos" required/>
                                                <small class="text-muted">
                                                    Kamu dapat memilih lebih dari satu file
                                                </small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-2">
                                <div class="col">
                                    <button type="submit" class="btn btn-success btn-block px-5">
                                        Save Now
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/product-galleries/edit.blade.php
@extends('backend.include.app')

@section('content')

    <div class="section-content section-dashboard-home" >
        <div class="container-fluid">
            <div class="dashboard-heading">
                <h2 class="dashboard-title">Add New Menu</h2>
                <p class="dashboard-subtitle">
                    Create my own menu
                </p>
            </div>
            <div class="dashboard-content">
                <div class="row">
                    <div class="col-12">
                        <form action="{{ route('product-galleries.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class=" form-group">
                                                <label>Menu</label>
                                                <select name="Products_id" class="form-control">
                                                        <option value="{{ $data->id }}">{{ $data->product->ProductName }}
                                                        </option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="thumbnails">Thumbnails</label>
                                                <input type="file" multiple class="form-control pt-1" id="thumbnails"
                                                    aria-describedby="thumbnails" name="Photos" />
                                                <small class="text-muted">
                                                    Kamu dapat memilih lebih dari satu file
                                                </small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-2">
                                <div class="col">
                                    <button type="submit" class="btn btn-success btn-block px-5">
                                        Save Now
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/product-galleries/index.blade.php
@extends('backend.include.app')

@section('title')
    Store Dashboard
@endsection

@section('content')
    <!-- Section Content -->
    <div class="section-content section-dashboard-home" >
        <div class="container-fluid">
            <div class="dashboard-heading">
                <h2 class="dashboard-title">Menu Gallery</h2>
                <p class="dashboard-subtitle">
                    List of Gallery
                </p>
            </div>
            <div class="dashboard-content">
                <div class="row">
                    <div class="col-md-12">
                    @if (session('message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>Selamat!</strong> {{ session('message') }}
                    </div>
                    @endif

                        <div class="card">
                            <div class="card-body">
                                <a href="{{ route('product-galleries.create') }}" class="btn btn-primary mb-3">
                                    + Add New Gallery 
                                </a>
                                <div class="table-responsive">
                                    <table class="table table-hover scroll-horizontal-vertical w-100" id="crudTable">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Menu</th>
                                                <th>Photos</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($data as $item)
                                            {{-- menghilangkan foto yang menjadi thumbnail --}}
                                                @if($item->Photos != $item->product->ThumbnailPhoto)
                                                <tr>
                                                    <td>
                                                        {{ $item->id }}
                                                    </td>
                                                    <td>
                                                        {{ $item->product->ProductName }}
                                                    </td>
                                                    <td>
                                                        <img src="{{ asset('foto/' . $item->Photos) }}" alt=""

                                                            class="img-thumbnail" width="100px" height="80px">
                                                    </td>
                                                    <td>
                                                            <form action="{{route('product-galleries.destroy',$item->id)}}" method="POST" enctype="multipart/form-data" class="d-inline">
                                                            @csrf
                                                            @method('DELETE')
                                                                <button type="submit" class="d-inline btn btn-warning"> Delete </button>
                                                            </form>
                                                    </td>
                                                </tr>
                                                @endif
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('addon-script')
    <script>
        // AJAX DataTable
        var datatable = $('#crudTable').DataTable({
            processing: true,
            serverSide: true,
            ordering: true,
            ajax: {
                url: '{!! url()->current() !!}',
            },
            columns: [{
                    data: 'id',
                    name: 'id'
                },
                {
                    data: 'product.name',
                    name: 'product.name'
                },
                {
                    data: 'photos',
                    name: 'photos'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false,
                    width: '15%'
                },
            ]
        });

    </script>
@endpush