routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductGalleriesController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\LaporanController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\LandingPageController::class, 'index'])->name('landingpage');
Route::get('/detail/{id}', [App\Http\Controllers\LandingPageController::class, 'detail'])->name('detail');
Route::post('/detail/{id}', [App\Http\Controllers\LandingPageController::class, 'add'])->name('detail-add');

Route::get('/categories', [App\Http\Controllers\LandingPageController::class, 'categories'])->name('categories');

Route::post('/addreview/{id}',[App\Http\Controllers\LandingPageController::class, 'addreview'])->name('addreview');
Route::get('/orderhistory',[App\Http\Controllers\LandingPageController::class, 'orderhistory'])->name('order-history');
Route::put('/uploadBukti', [App\Http\Controllers\LandingPageController::class, 'uploadBukti'])->name('uploadBukti');
Route::post('/addBukti', function(Request $request){
    $request->validate([
        'user_id' => 'required',
        'id_transaksi' => 'required',
        'file' => 'required',
        'file.*' => 'mimes:doc,docx,PDF,pdf,jpg,jpeg,png|max:2000'
    ]);
    if ($request->hasfile('file')) {            
        $filename = str_replace(' ','-',$request->file('file')->getClientOriginalName());
        $request->file('file')->move(\storage_path('bukti'), $filename);
        Pembayaran::insert([                        
            'id_transaksi' => $request->id_transaksi,
            'user_id' => $request->user_id,
            'image' =>$filename,
        ]);
        return redirect('/orderhistory');
    }else{
        echo'Gagal';
    }
})->name('addBukti');
Route::post('/show-order/{id}',[App\Http\Controllers\LandingPageController::class, 'ordershow'])->name('ordershow');
Route::get('/about-me',[App\Http\Controllers\LandingPageController::class, 'aboutme'])->name('aboutme');


Auth::routes();

Route::post('/home/upload', [HomeController::class, 'index'])->name('upload');

Route::middleware(['auth', 'admin'])
    ->group(function() {

Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::resource('product', ProductController::class);
Route::resource('transaction', TransactionController::class);
Route::resource('product-galleries', ProductGalleriesController::class);
Route::get('laporan', [LaporanController::class, 'index']);

    });

Route::resource('cart', CartController::class);

Route::post('/checkout', [App\Http\Controllers\CheckoutController::class, 'process'])->name('checkout');
Route::post('/checkout/callback', [App\Http\Controllers\CheckoutController::class, 'callback'])->name('midtrans-callback');
Route::post('/order', [App\Http\Controllers\CheckoutController::class, 'order'])->name('order');

Route::post('/checkoutdata', [App\Http\Controllers\CheckoutController::class, 'checkoutdata'])->name('checkoutdata');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
//
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    //
    use SoftDeletes;

    use HasFactory;
    protected $fillable = [
        'ProductName',
        'Price',
        'Description',
        // 'Image',
        'Categories',
        'Weight',
        'ThumbnailPhoto'
    ];

     public function galleries(){
        return $this->hasMany( ProductGallery::class, 'Products_id', 'id' );
    }
        public function user(){
        return $this->hasOne( User::class, 'id', 'users_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\ProductGallery;
use App\Models\Cart;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\QueryException;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data =  Product::with('galleries')->get();
        return view('backend.product.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //untuk validasi form
        $validated = $request->validate([
            'ProductName' => 'required',
            'Price' => 'required|integer',
            'Categories' => 'required',
            'Weight' => 'required|integer',
            'Description' => 'required',
            'ThumbnailPhoto.*' => 'required|mimes:jpg,jpeg,png',
        ]);

        // $data =  $request->all();
        // $data['ThumbnailPhoto'] = $request->file('ThumbnailPhoto')[0]->store('assets/product', 'public',$request->file('ThumbnailPhoto')[0]->GetClientOriginalName());
        // $image = $request->file('ThumbnailPhoto');
        // $fileName = $image->getClientOriginalName();
        // $request->file('ThumbnailPhoto')->move(\public_path('storage'), $fileName);
        // $data = $request->all();
        // $product =  Product::create($data);

                   
        $filename = str_replace(' ','-',$request->file('ThumbnailPhoto')->getClientOriginalName());
        $request->file('ThumbnailPhoto')->move(\public_path('foto'), $filename);
        $product =  Product::create([
            'ProductName' => $request->ProductName,
            'Price' => $request->Price,
            'Weight' => $request->Weight,
            'Categories' => $request->Categories,
            'Description' => $request->Description,
            'ThumbnailPhoto' => $filename,
        ]);

        $gallery = [
            'Products_id' => $product -> id,
            'Photos' =>  $filename,
        ];
        ProductGallery::create($gallery);
        return redirect('/product')->with('message', 'Data telah ditambahkan');



        // $gallery = [
        //     'Products_id' => $product -> id,
        //     'Photos' =>  $request->file('ThumbnailPhoto')->store('assets/product', 'public'),
        // ];

        // ProductGallery::create($gallery);

        // foreach($request->file('ThumbnailPhoto') as $foto){
        //     $gallery = [
        //         'Products_id' => $product -> id,
        //         'Photos' =>  $foto->store('assets/product', 'public'),
        //     ];
    
        //     ProductGallery::create($gallery);
        // }

        // return redirect('/product')->with('message', 'Data telah ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Product::findOrFail($id);
        return view('backend.product.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //contoh jika error messagenya diubah
        $validated = $request->validate([
            //nama input sama dengan yang ada di view
            'ProductName' => 'required',
            'Price' => 'required|integer',
            'Categories' => 'required',
            'Weight' => 'required|integer',
            'Description' => 'required',
            'ThumbnailPhoto' => 'mimes:jpg,jpeg,png',
        ],[
            // 'namainput.rule' => 'custom error message'
            'Description.required' => 'Deskripsi belum diisi',
            'ThumbnailPhoto.mimes' => 'File bukan foto'
        ]);

        if(empty($request->ThumbnailPhoto)){
            $item = Product::findOrFail($id);
            $data = $request->all();
            $insert =  $item->update($data);
        }
        else{
            $item = Product::findOrFail($id);
            $data = $request->all();
            // $data['ThumbnailPhoto'] = $request->file('ThumbnailPhoto')->store('assets/product', 'public',$request->file('ThumbnailPhoto')->GetClientOriginalName());
            $data['ThumbnailPhoto'] = str_replace(' ','-',$request->file('ThumbnailPhoto')->getClientOriginalName());
            $request->file('ThumbnailPhoto')->move(\public_path('foto'), $data['ThumbnailPhoto']);
    
            //ubah thumbnail pada gallery
            ProductGallery::where('Products_id',$id)->where('Photos',$item->ThumbnailPhoto)->update(['Photos'=>$data['ThumbnailPhoto']]);

            $insert =  $item -> update($data);
        }
     

        return redirect('/product')->with('message', 'Data telah diupdate');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //bug cart
        Cart::with('Product')->where('Products_id',$id)->delete();
        ProductGallery::with('Product')->where('Products_id',$id)->delete();
        Product::findOrFail($id)->delete();
        
        return redirect('/product')->with('message', 'Data telah dihapus');
    }
}

resources/views/backend/product/create.blade.php
@extends('backend.include.app')

@section('content')

    <div class="section-content section-dashboard-home">
        <div class="container-fluid">
            <div class="dashboard-heading">
                <h2 class="dashboard-title">Add New Menu</h2>
                <p class="dashboard-subtitle">
                    Create my own menu
                </p>
            </div>
            <div class="dashboard-content">
                <div class="row">
                    <div class="col-12">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="name">Menu Name</label>
                                                <input type="text" class="form-control" id="name" aria-describedby="name"
                                                    name="ProductName" required placeholder="Nama Menu"/>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="price">Price</label>
                                                <input type="number" class="form-control" id="price"
                                                    aria-describedby="price" name="Price" placeholder="Price" required/>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="categories">Category</label>
                                                <select class="form-control" id="category" name="Categories">
                                                    <option value="0" disabled="true" selected="true">Pilih Category</option>
                                                    <option>Dessert Box</option>
                                                    <option>Dessert Cup</option>
                                                    <option>Baked Brownies</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="categories">Weight (Gr) </label>
                                                <input type="number" class="form-control" id="price"
                                                    aria-describedby="price" name="Weight" placeholder="Weight(Gr)" required/>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="description">Descriptions</label>
                                                <textarea name="Description" id="" cols="30" rows="4"
                                                    class="form-control" required placeholder="Keterangan"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="thumbnails">Thumbnails</label>
                                                <input type="file" multiple class="form-control pt-1" id="thumbnails"
                                                    aria-describedby="thumbnails" name="ThumbnailPhoto"/>
                                                <small class="text-muted">
                                                    Kamu dapat memilih lebih dari satu file
                                                </small>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-success btn-block px-5">
                                                    Save Now
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
@endsection

resources/views/backend/product/edit.blade.php
@extends('backend.include.app')

@section('content')

    <div class="section-content section-dashboard-home">
        <div class="container-fluid">
            <div class="dashboard-heading">
                <h2 class="dashboard-title">Add New Menu</h2>
                <p class="dashboard-subtitle">
                    Create my own menu
                </p>
            </div>
            <div class="dashboard-content">
                <div class="row">
                    <div class="col-12">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('product.update',$data -> id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="name">Menu Name</label>
                                                <input type="text" class="form-control" id="name" aria-describedby="name"
                                                    name="ProductName" value="{{ $data -> ProductName}}" required/>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="price">Price</label>
                                                <input type="number" class="form-control" id="price"
                                                    aria-describedby="price" name="Price" value="{{$data -> Price}}" required/>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="categories">Category</label>
                                                <select class="form-control" id="category" name="Categories">
                                                    <option>{{$data -> Categories}}</option>
                                                    @if ($data -> Categories == 'Dessert Cup')
                                                    <option>Baked Brownies</option>
                                                    <option>Dessert Box</option>
                                                    @elseif($data -> Categories == 'Baked Brownies') 
                                                    <option>Dessert Cup</option>
                                                    <option>Dessert Box</option>
                                                    @else
                                                    <option>Dessert Cup</option>
                                                    <option>Baked Brownies</option>
                                                    @endif
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="categories">Weight (Gr) </label>
                                                <input type="number" class="form-control" id="price"
                                                    aria-describedby="price" name="Weight" value="{{ $data -> Weight}}" required/>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="description">Descriptions</label>
                                                <textarea name="Description" id="" cols="30" rows="4"
                                                    class="form-control" required> {{$data -> Description }}</textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="thumbnails">Thumbnails</label>
                                                <input type="file" multiple class="form-control pt-1" id="thumbnails"
                                                    aria-describedby="thumbnails" name="ThumbnailPhoto" accept=".png, .jpeg, .jpg"/>
                                                <small class="text-muted">
                                                    Kamu dapat memilih Gambar untuk thumbnail
                                                </small>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-success btn-block px-5">
                                                    Save Now
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
@endsection

resources/views/backend/product/index.blade.php
@extends('backend.include.app')

@section('content')


    <div class="section-content section-dashboard-home">
        <div class="container-fluid">
            <div class="dashboard-heading">
                <h2 class="dashboard-title">My Menu</h2>
                <p class="dashboard-subtitle">
                    Manage it well and get money
                </p>
            </div>
            <div class="dashboard-content">
                <div class="row">
                    <div class="col-12">
                        <a href="{{ route('product.create') }}" class="btn btn-success">Add New Menu</a>
                    </div>
                    <div class="col-12">
                        @if (session('message'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>Selamat!</strong> {{ session('message') }}
                        </div>
                        @endif
                    </div>

                </div>
                <div class="row mt-4">
                    @foreach ($data as $item)
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                            <a class="card card-dashboard-product d-block" href="{{ route('detail', $item->id) }}">
                                <div class="card-body">
                                    @if (!$item->galleries->isEmpty())
                                        <img src="{{ asset('foto/' . $item->ThumbnailPhoto) }}" alt=""
                                            height="200px" class="w-100 mb-2" />
                                    @else
                                        <img src="" alt="" height="140px" class="w-100 mb-2" />
                                    @endif
                                    <div class="product-title">{{ $item->ProductName }}</div>
                                    <div class="product-category">{{ $item->Categories }}</div>
                                </div>
                                <a href="{{ route('product.edit',$item->id)}}" class="btn btn-info"> Edit </a>
                                <form action="{{ route('product.destroy',$item -> id) }}" method="POST" class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-warning"> Delete </button>
                                </form>
                            </a>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

@endsection